INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('1', '¿Cuánto dura un partido de fútbol?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('1', '¿Cuándo se celebró el primer mundial de fútbol?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('1', '¿Qué selección de fútbol ha ganado más Mundiales?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('1', '¿En qué ciudad se encuentra el estadio popularmente conocido como La Bombonera?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('1', '¿Cuál es el apodo del Leicester City?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('2', '¿Cuánto dura la prórroga en un partido de fútbol?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('2', '¿Cuántos jugadores tiene un equipo de fútbol en el campo de juego?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('2', '¿Cuál es el estadio de fútbol con mayor capacidad del mundo?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('2', '¿Quién ganó el mundial de fútbol de 2010?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('2', '¿Qué número llevaba a la espalda Raúl González del Real Madrid?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('3', '¿Quién es el máximo goleador del FC Barcelona?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('3', '¿Qué equipos componen el derbi sevillano?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('3', '¿En qué club italiano jugó Diego Maradona?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('3', '¿De qué ciudad es el Chelsea Football Club?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('3', '¿De qué colores es la camiseta del Atlético de Madrid?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('4', '¿Qué equipo de la Premier League tiene más ligas ganadas?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('4', '¿Qué revista concede el Balón de Oro?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('4', '¿Cómo se llama el estadio del Bayern de Munich?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('4', '¿Qué selección ganó la Copa Mundial de Fútbol en Francia 98?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('4', '¿En qué año debutó Pep Guardiola como entrenador del FC Barcelona?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('5', '¿Cuál es el equipo más famoso de la ciudad italiana de Turín?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('5', '¿Qué entrenador argentino es conocido como "El Cholo"?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('5', '¿Cuál es el único equipo de fútbol español que ha ganado todos los títulos oficiales en una temporada?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('5', '¿En qué posición juega el cancerbero de un equipo de fútbol?');
INSERT INTO preguntas (`categoria_pregunta`, `desc_pregunta`) VALUES ('5', '¿Qué país ha ganado más Eurocopas seguidas?');
