INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'A. 100 minutos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'B. 98 minutos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'C. 90 minutos', b'1', '1000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'D. 60 minutos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'A. El 13 de julio de 1930', b'1', '1000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'B. El 13 de julio de 1934', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'C. El 11 de junio de 1930', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'D. El 13 de enero de 1939', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'A. Brasil ', b'1', '1000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'B. Argentina ', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'C. Italia ', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'D. España ', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'A. Buenos Aires, España', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'B. Buenos Aires, Argentina', b'1', '1000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'C. medellín, Colombia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'D. José María Córdoba', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'A. Claveles', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'B. Tulipánes', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'C. The Foxes, los zorros', b'1', '1000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'D. los lobos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'A. 30 minutos', b'1', '2000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'B. 20 minutos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'C. 15 minutos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'D. 18 minutos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'A. 11', b'1', '2000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'B. 15', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'C. 12', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'D. 10', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'A. Santiago Bernabeu', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'B. Bombonera', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'C. Reungrado Primero de Mayo', b'1', '2000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'D. Atanasio Girardot', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'A. España', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'B. Brasil', b'1', '2000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'C. Italia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'D. Alemania', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'A. 70', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'B. 6', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'C. 11', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'D. 7', b'1', '2000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'A. Xavi', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'B. Piqué', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'C. Iniesta', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'D. Lionel Messi', b'1', '3000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'A. Sevilla Fútbol Club y Real Betis Balompié', b'1', '3000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'B. Barcelona y sevilla', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'C. Real Betis y Barcelona', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'D. Sevilla y Real Madrid', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'A. Milan', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'B. Juventus', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'C. Nápoli', b'1', '3000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'D. Genoa', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'A. Fulham, Londres', b'1', '3000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'B. Milan, Italia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'C. Madrid, España', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'D. Paris, Francia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'A. Verde y Blanco', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'B. Rojo y negro', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'C. Rojo y blanco', b'1', '3000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'D. Azul y Amarillo', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'A. Manchester City', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'B. Manchester United', b'1', '4000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'D. Liverpool', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'E. Chelsee', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'A. France Football', b'1', '4000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'B. Play boy', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'C. La guerra de los supremos', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'D. La U', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'A. Santiago Bernabeu', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'B. Atanasio Girardot', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'C. Allianz Arena', b'1', '4000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'D. Metropolitano', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'A. Francia', b'1', '4000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'B. Inglaterra', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'C. Brasil', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'D. Italia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'A. 2010', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'B. 2000', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'C. 2009', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'D. 2008', b'1', '4000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'A. Milan', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'B. Atalanta', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'C. Juventus', b'1', '5000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'D. Niza', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'A. Sidane', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'B. Pep Guardiola', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'C. Diego Maradona', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'D. Diego Simeone', b'1', '5000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'A. Real Madrid FC', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'B. FC Barcelona', b'1', '5000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'C. Sevilla FC', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'D. Rayo Vallecano', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'A. Defensa', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'B. Volante', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'C. Portero', b'1', '5000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'D. Delantero', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'A. Italia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'B. Francia', b'0', '0');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'C. España', b'1', '5000');
INSERT INTO respuestas (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'D. Alemania', b'0', '0');